parameters:
    logger.handler.stream.output: unteist.log
    logger.handler.stream.level: DEBUG
    logger.name: unteist

services:
    logger:
        class: \Monolog\Logger
        arguments: [ %logger.name% ]
    logger.handler.stream:
        class: \Monolog\Handler\StreamHandler
        arguments: [ %logger.handler.stream.output%, %logger.handler.stream.level% ]
    logger.handler.null:
        class: \Monolog\Handler\NullHandler
    reporter:
        class: \Unteist\Report\Twig\TwigReport
        arguments: [ %report.dir% ]
    strategy.fail:
        class: \Unteist\Strategy\TestFailStrategy
    strategy.incomplete:
        class: \Unteist\Strategy\IncompleteTestStrategy
    strategy.continue:
        class: \Unteist\Strategy\DoNothingStrategy
    filter.class.base:
        class: \Unteist\Filter\ClassFilter
    filter.methods.base:
        class: \Unteist\Filter\MethodsFilter
    filter.methods.group:
        class: \Unteist\Filter\GroupMethodsFilter
    context:
        class: \Unteist\Strategy\Context
    dispatcher:
        class: \Symfony\Component\EventDispatcher\EventDispatcher
    storage.global:
        class: \ArrayObject