parameters:
    logger.handler.stream.output: unteist.log
    logger.handler.stream.level: DEBUG
    logger.name: unteist
    connector.events: []

services:
    logger:
        class: \Monolog\Logger
        arguments: [ %logger.name% ]
        synthetic: true
    logger.handler.stream:
        class: \Monolog\Handler\StreamHandler
        arguments: [ %logger.handler.stream.output%, %logger.handler.stream.level% ]
    logger.handler.null:
        class: \Monolog\Handler\NullHandler
    reporter:
        class: \Unteist\Report\Twig\TwigReport
        arguments: [ %report.dir% ]
    strategy.fail:
        class: \Unteist\Strategy\TestFailStrategy
    strategy.continue:
        class: \Unteist\Strategy\ContinueStrategy
    strategy.exception:
        class: \Unteist\Strategy\ExceptionStrategy
    filter.class.base:
        class: \Unteist\Filter\ClassFilter
    filter.methods.base:
        class: \Unteist\Filter\MethodsFilter
    filter.methods.group:
        class: \Unteist\Filter\GroupMethodsFilter
    context:
        class: \Unteist\Strategy\Context
        synthetic: true
    dispatcher:
        class: \Symfony\Component\EventDispatcher\EventDispatcher
    storage.global:
        class: \ArrayObject
    connector:
        class: \Unteist\Event\Connector
        arguments: [ @dispatcher, %connector.events% ]
    runner:
        class: \Unteist\Processor\Runner
        scope: prototype
        synthetic: true
    processor:
        class: \Unteist\Processor\Processor
        synthetic: true
        calls:
            - [ setContainer, [ @container ] ]
    processor.multi:
        class: \Unteist\Processor\MultiProcessor
        calls:
            - [ setContainer, [ @container ] ]
            - [ setConnector, [ @connector ] ]
        synthetic: true
    controller:
        abstract: true
        calls:
            - [ setDispatcher, [ @dispatcher ] ]
            - [ setContainer, [ @container ] ]
    controller.skip:
        parent: controller
        class: \Unteist\Processor\Controller\SkipTestsController
    controller.run:
        parent: controller
        class: \Unteist\Processor\Controller\RunTestsController
        calls:
            - [ setContext, [ @context ] ]
    event.method:
        class: \Unteist\Event\MethodEvent
        scope: prototype